# Generated by Django 4.2 on 2024-09-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='fecha_y_hora',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.CharField(max_length=100),
        ),
    ]
